# -*- coding: utf-8 -*-
"""PythonOne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNJP-Yz3dKwal3sx96BfwWq7pCsPRNJL
"""

1+1

# Variables
a = 10
a

type(a)

# Complex number
# 4 is the real number and 7j is the imaginary part (where j is the notation for imaginary part)
cNum = 4 + 7j
type(cNum)

cNum.real

cNum.imag

c = True

True + True

# Single line comment

"""Multi line comment
Multi line comment
Multi line comment
Multi line comment
Multi line comment"""

strVar = "My name is Sidd"
type(strVar)

print(strVar)

s = '''Day's Name's "Double Quote" are here'''
print(s)

# to print physicalmenory location of the string
id(s)

myStr = "Siddhartha"

# in python we can access data in both forward and backward direction as well.

# Forward direction
print("Forward Direction =====>")
print(myStr[0])
print(myStr[2])
print(myStr[3])
print(myStr[4])
print(myStr[5])
print(myStr[6])
print(myStr[7])
print(myStr[8])
print(myStr[9])

# Backward Direction
print("Backward Direction =====>")
print(myStr[-1])
print(myStr[-2])
print(myStr[-3])
print(myStr[-4])
print(myStr[-5])
print(myStr[-6])
print(myStr[-7])
print(myStr[-8])
print(myStr[-9])
print(myStr[-10])

# String Slicing Operations

# Provided starting point and end point (for string always excludeds upper bound)
print(myStr[0:5])
print(myStr[3:9])

# Start,End and Step
print(myStr[0:5:2])
print(myStr[3:9:2])
print(myStr[3:9:3])
print(myStr[-2:-9:-2])

# Moving towards negative direction will give data

print(myStr[5:0:-1])
print(myStr[5:0:-2])

# Reverse a String
reversedString = myStr[::-1]
print(reversedString)

print(myStr.count('t'))
print(myStr.count('d'))

# List (Array is known as list in python)

listOne = []
print(type(listOne))

listTwo = list()
print(type(listTwo))


listThree = [1, 20, "Sidd", "Sarkar", 45.45, True, 5 + 8j, [4, 5 , 6, "fdfs"]]

print(listThree)

print(listThree[3])
print(listThree[-4])

print(type(listThree[-4]))
print(type(listThree[6]))

print(listThree[7][3])
print(type(listThree[7][3]))

print(listThree[0:7])

# for below cod the output will be blank as bt default the third argument will be positive 1. So we need to specify the 3rd argumentas negative 1.
print(listThree[-1:-5])

print(listThree[-1:-5:-1])
print(listThree[-1:-5:-2])

print(listThree[0:-5:-1])
print(listThree[0:-5:1])